DROP TABLE IF EXISTS books;
DROP TABLE IF EXISTS posts;

CREATE TABLE books(
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    created TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    title TEXT NOT NULL,
    author TEXT NOT NULL
)
